language: node_js
node_js:
  - "node"
  - "lts/*"
  - "8"
before_script:
  - yarn prepare
  - yarn install
script:
  #  - yarn test
  #  - node lib/cli.js --version
  #  - node lib/cli.js test/fixtures/valid.graphql
  - ls && ls bin
notifications:
  email: false
